NAME= 	Chat
TYPE= 	APP
SRCS=   App.cpp \
		MainWindow.cpp ChatWindow.cpp BuddyWindow.cpp DataForm.cpp \
		ModalAlertFactory.cpp \
		SplitView.cpp ChatTextView.cpp StatusView.cpp RosterView.cpp \
		RosterItem.cpp RosterSuperitem.cpp PeopleListItem.cpp UserID.cpp \
		TalkManager.cpp JabberProtocol.cpp \
		MessageRepeater.cpp \
		EditingFilter.cpp \
		GenericFunctions.cpp \
		Settings.cpp \
		XMLEntity.cpp XMLReader.cpp FileXMLReader.cpp \
		Socket.cpp SecureSocket.cpp \
		Base64.cpp
RSRCS= 	Resources.rsrc
LIBS= 	/boot/system/lib/libbe.so \
		/boot/system/lib/libroot.so \
		/boot/system/lib/libnetwork.so \
		/boot/system/lib/libtranslation.so \
		/boot/system/develop/lib/libssl.so \
		/boot/system/develop/lib/libcrypto.so \
		/boot/system/develop/lib/libexpat.so \
		/boot/system/lib/libstdc++.r4.so
LIBPATHS=
OPTIMIZE=FULL
DEFINES=
WARNINGS =
SYMBOLS=
COMPILER_FLAGS=-s
LINKER_FLAGS=
SYSTEM_INCLUDE_PATHS= /boot/develop/headers/be
LOCAL_INCLUDE_PATHS= /boot/system/develop/headers

include $(BUILDHOME)/etc/makefile-engine
