NAME= Chat
TYPE= APP
SRCS= App.cpp \
		ChatTextView.cpp \
		JRoster.cpp \
		RosterItem.cpp \
		UserID.cpp \
		BuddyWindow.cpp \
		PeopleListItem.cpp \
		TalkManager.cpp \
		StatusView.cpp \
		RosterView.cpp \
		RosterSuperitem.cpp \
		ModalAlertFactory.cpp \
		XMLEntity.cpp \
		Settings.cpp \
		MessageRepeater.cpp \
		XMLReader.cpp \
		FileXMLReader.cpp \
		MainWindow.cpp \
		ChatWindow.cpp \
		EditingFilter.cpp \
		GenericFunctions.cpp \
		Socket.cpp \
		DataForm.cpp \
		SecureSocket.cpp \
		JabberProtocol.cpp \
		SplitView.cpp \
		Base64.cpp
RSRCS= Resources.rsrc
LIBS= /boot/system/lib/libbe.so /boot/system/lib/libroot.so /boot/system/develop/lib/libssl.so /boot/system/develop/lib/libcrypto.so /boot/system/lib/libnetwork.so /boot/system/lib/libtranslation.so /boot/system/develop/lib/libexpat.so /boot/system/lib/libstdc++.r4.so
LIBPATHS=
SYSTEM_INCLUDE_PATHS= /boot/develop/headers/be
LOCAL_INCLUDE_PATHS= boot/system/develop/headers
OPTIMIZE=FULL
DEFINES=
WARNINGS =
SYMBOLS=
COMPILER_FLAGS=
LINKER_FLAGS=

include $(BUILDHOME)/etc/makefile-engine
